/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // 左侧边栏，可以添加任意HTML代码，图片，并结合autogenerated侧边栏。实现自动生成和自定义的结合
  zidongSidebar: [

    {
      type: 'html',
      value: '<img src="img/VBA-logo.webp" /> <hr>', // The HTML to be rendered
      defaultStyle: true, // Use the default menu item styling
    },

    {
      type: 'autogenerated',
      dirName: '.'
    },
    // {
    //   type: 'link',
    //   label: 'Chat with us on Discord',
    //   href: 'https://discord.gg/dd',
    // },
    // {
    //   type: 'html',
    //   value: '<img src="img/grass.png" />', // The HTML to be rendered
    //   defaultStyle: true, // Use the default menu item styling
    // },
  ],

  // But you can create a sidebar manually  
};

module.exports = sidebars;
